name: receiver
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.1.2

# Add regular dependencies here.
dependencies:
  at_client: ^3.0.63
  at_onboarding_cli: ^1.3.0
  at_utils: ^3.0.15
  version: ^3.0.2
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
